// Phase 4 Revision - Intake Step 3: Brief (inline-editable) + canonical Brief
// surface.
//
// Third step of the brief stepper AND the permanent Brief surface a scout
// keeps for the rest of its life. Renders the brief as a hero band + a stack
// of inline-editable cards. Every card flips to edit mode on click and
// persists on Save. The Event Overview block is generated by
// vs-generate-brief-overview on the Submit Brief click in BriefVenue.tsx
// (Phase 4 Revision pass 3), re-invokable here via the Regenerate link; the
// empty-state Generate button is the manual fallback for scouts that reached
// the report without going through Submit Brief.
//
// Two modes:
//   - Intake mode (current_step === 'brief'): the footer shows Confirm &
//     Continue, which flips current_step brief -> sheet_prompt and advances.
//   - Permanent-surface mode (current_step past 'brief'): same page, but the
//     Confirm & Continue button is hidden. The Revisit nav surfaces this page
//     from elsewhere in the flow.
import { useCallback, useEffect, useRef, useState } from "react";
import {
  Link,
  useNavigate,
  useParams,
  useSearchParams,
} from "react-router-dom";
import { ArrowLeft, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Slider } from "@/components/ui/slider";
import { Checkbox } from "@/components/ui/checkbox";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import { ScoutPageHeader } from "@/components/venue-scout/ScoutPageHeader";
import { TagInput } from "@/components/venue-scout/TagInput";
import { ChipMultiSelect } from "@/components/venue-scout/ChipMultiSelect";
import { RecordCombobox } from "@/components/ui/RecordCombobox";
import { DateRangePicker } from "@/components/ui/DateRangePicker";
import { useCityIdForName } from "@/lib/hq/lookups";
import { stepToRoute } from "@/lib/venue-scout/format";
import {
  buildOverviewStub,
  fromScout,
  toUpdate,
  type BriefFormState,
  type PriorityCost,
  type PriorityLocation,
} from "@/lib/venue-scout/briefForm";
import { briefIntake } from "@/lib/venue-scout/briefIntakeStore";
import {
  GeneratedDecksCard,
  type DeckEntry,
} from "@/components/venue-scout/GeneratedDecksCard";
import { BriefReportRow } from "@/components/venue-scout/BriefReportRow";
import type { Database } from "@/integrations/supabase/types";

type VsScoutRow = Database["public"]["Tables"]["vs_scouts"]["Row"];

const SCOUT_SELECT =
  "id, client_name, event_name, live_dates, city, budget, event_overview, brief_data, current_step, archived_at, name, status, project_id, sheet_storage_path, derived_columns, generated_decks, deck_order, last_touched_at, created_at, created_by, updated_at, updated_by";

const SQ_FT_MAX = 10000;
const SQ_FT_STEP = 500;

const PRIORITY_LOCATION_LABEL: Record<PriorityLocation, string> = {
  high_foot_traffic: "High Foot Traffic",
  intimate_destination: "Intimate / Destination",
};
const PRIORITY_COST_LABEL: Record<PriorityCost, string> = {
  lower_cost: "Lower Venue Costs",
  premium: "Premium Venue",
};

// Phase 5.12.14 § 8.6: dynamic forward button on BriefReport. Maps the
// scout's `current_step` to the next-actionable phase. `advancesStep` is
// true only on the brief -> sheet_prompt transition (delegates to
// `requestConfirm` for the CAS-guarded state write); everything else is
// pure navigation. The `completed` case routes to deck_prep instead of
// `stepToRoute("completed")` because the latter returns /brief (a loop
// back to BriefReport).
type ForwardCta = {
  label: string;
  destStep:
    | "sheet_prompt"
    | "sheet_upload"
    | "researching"
    | "sourcing_report"
    | "shortlist"
    | "compiling"
    | "deck_prep"
    | "completed";
  advancesStep: boolean;
};

function resolveForwardCta(currentStep: string | null): ForwardCta {
  switch (currentStep) {
    case "brief":
      return {
        label: "Begin Sourcing →",
        destStep: "sheet_prompt",
        advancesStep: true,
      };
    case "sheet_prompt":
      // Producer has confirmed the brief but hasn't committed any sourcing
      // action yet (no sheet uploaded, no research kicked off). Still reads
      // as "Begin" — they haven't started sourcing in any meaningful way.
      return {
        label: "Begin Sourcing →",
        destStep: "sheet_prompt",
        advancesStep: false,
      };
    case "sheet_upload":
    case "researching":
    case "sourcing_report":
      // Sourcing in flight or candidate venues already sourced; switch to
      // "Go to" because there's existing state to return to, not start.
      return {
        label: "Go to Sourcing →",
        destStep:
          (currentStep as ForwardCta["destStep"]) ?? "sourcing_report",
        advancesStep: false,
      };
    case "shortlist":
      return {
        label: "Go to Shortlist →",
        destStep: "shortlist",
        advancesStep: false,
      };
    case "review_selects":
      // Phase 5.12.15 retired the standalone Final Review step from the
      // forward flow; legacy scouts still in this state route to the
      // consolidated Review surface (stepToRoute("review_selects") resolves
      // to /review per format.ts). NEVER fall to the default branch — that
      // would rewind these scouts to sheet_prompt via requestConfirm.
      return {
        label: "Go to Review →",
        destStep: "deck_prep",
        advancesStep: false,
      };
    case "compiling":
    case "deck_prep":
      return {
        label: "Go to Review →",
        destStep: (currentStep as ForwardCta["destStep"]) ?? "deck_prep",
        advancesStep: false,
      };
    case "completed":
      return {
        label: "Go to Review →",
        destStep: "deck_prep",
        advancesStep: false,
      };
    default:
      // Unknown / null current_step: assume a fresh scout in the brief intake
      // phase and let requestConfirm advance brief -> sheet_prompt. Every
      // KNOWN step is handled above; this branch only ever fires when scout
      // load races a render or carries a typo'd / future enum value.
      return {
        label: "Begin Sourcing →",
        destStep: "sheet_prompt",
        advancesStep: true,
      };
  }
}

// Phase 5.12.14.1 Stage 2C revision round 2 item 1 → R7 amendment v3 § 3:
// the dynamic-stage `resolveBriefReportCrumb` helper retired. The back-
// crumb now lives in the global TopBar via `useReferrerCrumb`'s canonical-
// parent table, which routes BriefReport → Brief Venue. If smoke surfaces
// real producer need for the stage-aware routing (Sourcing /Shortlist
// / Review depending on current_step), reinstate via a route-table
// extension in `useReferrerCrumb` that reads scout state.

export default function BriefReport() {
  const { id: scoutId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const [searchParams, setSearchParams] = useSearchParams();

  const [scout, setScout] = useState<VsScoutRow | null>(null);
  const [form, setForm] = useState<BriefFormState | null>(null);
  const [confirming, setConfirming] = useState(false);
  const [overviewStatus, setOverviewStatus] = useState<
    "idle" | "generating" | "regenerating"
  >("idle");
  // Phase 5.12.14.3 Round 2 amendment v2: the Overview card sheds the
  // BriefReportRow state machine (always-editable textarea). Local draft
  // tracks producer edits; save fires on blur when dirty. confirmRegen gates
  // Regenerate-while-dirty (discard-edits warning).
  const [overviewDraft, setOverviewDraft] = useState("");
  const [confirmRegen, setConfirmRegen] = useState(false);

  // Latest-form ref so async callbacks (overview generation) merge against the
  // current form, not a stale closure capture -- a card edit can land while
  // the overview is generating.
  const formRef = useRef<BriefFormState | null>(form);
  formRef.current = form;

  // Phase 5.12.14.3 amendment v3 § I: Overview textarea auto-grows to fit
  // content (no internal scroll). Hand-rolled scrollHeight measure pattern;
  // resets to auto then sets to scrollHeight after every overviewDraft
  // change. No new dep.
  const overviewTextareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    if (!scoutId) return;
    let active = true;
    (async () => {
      const { data, error } = await supabase
        .from("vs_scouts")
        .select(SCOUT_SELECT)
        .eq("id", scoutId)
        .maybeSingle();
      if (!active) return;
      if (error || !data) {
        toast({
          title: "Could not load scout",
          description: error?.message ?? "Scout not found",
          variant: "destructive",
        });
        return;
      }
      setScout(data as VsScoutRow);
      const f = fromScout(data as VsScoutRow);
      briefIntake.seed(scoutId, f);
      setForm(f);
    })();
    return () => {
      active = false;
    };
  }, [scoutId]);

  // Persist a form patch to the scout. Every inline card edit + the Overview
  // block route through here. Writes the full toUpdate payload (cheap: a few
  // columns + one jsonb) so the report stays consistent.
  const saveForm = useCallback(
    async (next: BriefFormState) => {
      if (!scoutId) return false;
      // Optimistic local update so the card flips back to display mode with
      // the new value immediately.
      setForm(next);
      briefIntake.commit(scoutId, next);
      const { error } = await supabase
        .from("vs_scouts")
        .update({
          ...toUpdate(next),
          last_touched_at: new Date().toISOString(),
          updated_by: user?.id ?? null,
        })
        .eq("id", scoutId);
      if (error) {
        toast({
          title: "Save failed",
          description: error.message,
          variant: "destructive",
        });
        return false;
      }
      return true;
    },
    [scoutId, user?.id],
  );

  // Event Overview generation. The edge function reads the scout's brief
  // fields, writes event_overview + brief_data.overview_source_hash to the row
  // atomically, and returns both. Invoked here by the empty-state Generate
  // button and the Regenerate link; the Submit Brief click in BriefVenue.tsx
  // is the primary trigger (Phase 4 Revision pass 3).
  const runOverviewGeneration = useCallback(
    async (mode: "generating" | "regenerating") => {
      if (!scoutId || !formRef.current) return;
      setOverviewStatus(mode);
      const { data, error } = await supabase.functions.invoke(
        "vs-generate-brief-overview",
        { body: { scout_id: scoutId } },
      );
      const responseError =
        error?.message ?? (data as { error?: string } | null)?.error ?? null;
      // Read the latest form AFTER the await -- a card edit may have landed
      // while the function was running.
      const latest = formRef.current;
      if (!latest) {
        setOverviewStatus("idle");
        return;
      }
      if (responseError) {
        // Invoke-level failure: the function never ran. Fall back to the
        // client stub so the producer always has a starting overview.
        // overview_source_hash is intentionally NOT written here (unlike
        // BriefVenue's Submit Brief failure path, which writes it to stop a
        // resubmit loop): Generate / Regenerate are already unconditional
        // re-invokes with no hash gate, and leaving the hash stale-or-missing
        // means the next Submit Brief will retry the generation.
        const stub = buildOverviewStub(latest);
        await saveForm({ ...latest, event_overview: stub });
        toast({
          title: "Overview generation failed",
          description: "Filled a basic overview you can edit.",
          variant: "destructive",
        });
        setOverviewStatus("idle");
        return;
      }
      const overview =
        typeof (data as { event_overview?: unknown } | null)?.event_overview ===
        "string"
          ? ((data as { event_overview: string }).event_overview)
          : "";
      const returnedHash =
        typeof (data as { overview_source_hash?: unknown } | null)
          ?.overview_source_hash === "string"
          ? (data as { overview_source_hash: string }).overview_source_hash
          : null;
      // The function already persisted event_overview + overview_source_hash;
      // sync local state + the cross-step store against the latest form inside
      // the updater so a concurrent card edit isn't clobbered.
      setForm((f) => {
        if (!f) return f;
        const next = {
          ...f,
          event_overview: overview,
          brief_data:
            returnedHash !== null
              ? { ...f.brief_data, overview_source_hash: returnedHash }
              : f.brief_data,
        };
        briefIntake.setForm(scoutId, next);
        return next;
      });
      setOverviewStatus("idle");
    },
    [scoutId, saveForm],
  );

  // Phase 5.12.14 § 8.7: post-deck-generate success toast. Generating.tsx
  // navigates to /brief/report?just-generated=true on success. Fire the
  // toast once on mount + strip the param via replace-state so a refresh
  // doesn't re-fire.
  useEffect(() => {
    if (searchParams.get("just-generated") === "true") {
      toast({
        title: "Deck generated",
        description: "Open in Google Slides below.",
      });
      const next = new URLSearchParams(searchParams);
      next.delete("just-generated");
      setSearchParams(next, { replace: true });
    }
  }, [searchParams, setSearchParams]);

  // Hooks must be called before any early return; resolve cityId for the
  // Neighborhoods row's RecordCombobox parent-scope (Phase 5.12.14.3 split
  // of the prior composite City row).
  const cityId = useCityIdForName(form?.city ?? "");

  // Keep the Overview textarea draft synced with the persisted value when it
  // changes from outside (initial load, generate completes, regenerate
  // completes). Producer edits in the textarea drive overviewDraft directly.
  useEffect(() => {
    setOverviewDraft(form?.event_overview ?? "");
  }, [form?.event_overview]);

  // Auto-grow the Overview textarea to fit content (amendment v3 § I).
  // Reset to auto first so shrinking on delete works; then read scrollHeight
  // and set it as the explicit pixel height. R6 § M.9: `overviewStatus`
  // added to the dep array so the effect re-fires when the textarea
  // remounts after the loading branch flips back to idle (the ref is
  // wired to the same DOM node, but the previous height computation may
  // have run while the loading panel was on screen).
  useEffect(() => {
    const ta = overviewTextareaRef.current;
    if (!ta) return;
    if (overviewStatus !== "idle") return;
    ta.style.height = "auto";
    ta.style.height = `${ta.scrollHeight}px`;
  }, [overviewDraft, overviewStatus]);

  // R6 § M.15: ResizeObserver re-measures on viewport resize so the
  // auto-grown height tracks line-wrap changes when the user resizes the
  // window. Single observer instance, cleaned up on unmount or status flip.
  useEffect(() => {
    const ta = overviewTextareaRef.current;
    if (!ta) return;
    const ro = new ResizeObserver(() => {
      if (overviewStatus !== "idle") return;
      ta.style.height = "auto";
      ta.style.height = `${ta.scrollHeight}px`;
    });
    ro.observe(ta);
    return () => ro.disconnect();
  }, [overviewStatus]);

  if (!scout || !form || !scoutId) {
    return <p className="text-sm text-muted-foreground">Loading…</p>;
  }
  const isArchived = scout.archived_at !== null;

  const decks = (
    Array.isArray(scout.generated_decks) ? scout.generated_decks : []
  ) as DeckEntry[];

  const heroSub = [form.city.trim(), form.live_dates.trim()]
    .filter(Boolean)
    .join(" · ");

  const requestConfirm = async () => {
    if (confirming) return;
    setConfirming(true);
    const { error } = await supabase
      .from("vs_scouts")
      .update({
        ...toUpdate(form),
        current_step: "sheet_prompt",
        last_touched_at: new Date().toISOString(),
        updated_by: user?.id ?? null,
      })
      .eq("id", scoutId);
    if (error) {
      setConfirming(false);
      toast({
        title: "Could not continue",
        description: error.message,
        variant: "destructive",
      });
      return;
    }
    briefIntake.reset();
    navigate(stepToRoute(scoutId, "sheet_prompt"));
  };

  const cardDisabled = isArchived;

  // Phase 5.12.14 § 8.6: derive the dynamic forward button + click handler.
  // requestConfirm owns the brief -> sheet_prompt advance (CAS-guarded write
  // via the existing handler); every other forward click is pure navigation.
  const cta = resolveForwardCta(scout.current_step);
  const onForwardClick = async () => {
    if (confirming) return;
    if (cta.advancesStep) {
      await requestConfirm();
      return;
    }
    navigate(stepToRoute(scoutId, cta.destStep));
  };

  // R7 amendment v3 § 3: per-page crumb fallback retired — the back-crumb
  // now lives in the global TopBar via useReferrerCrumb. BriefReport's
  // dynamic-stage crumb resolution (`resolveBriefReportCrumb` below)
  // currently has no consumer; the canonical fallback in
  // `useReferrerCrumb` routes BriefReport → Brief Venue. If the dynamic
  // routing is missed in smoke, extend useReferrerCrumb's route table
  // to read scout state.

  return (
    <div className="stack-6 pb-32">
      <header>
        {/* R7 amendment v2 § 5: shared ScoutPageHeader. */}
        <ScoutPageHeader scoutId={scout.id} scout={scout} />
      </header>

      {isArchived && (
        <div className="rounded-md border border-warn/40 bg-warn/10 px-4 py-3 text-sm text-warn">
          This scout is archived. Restore it from the Venue Scout index to edit the brief.
        </div>
      )}

      {/* ---- One outer card (amendment v3 § A) ---- */}
      {/* Hero moved into card-headbar; the page-level hero text block was
          retired. 2-col 70/30 .detail-2col--wide grid lives inside the
          outer card's .card-pad. Each column hosts labeled sub-sections,
          NOT nested cards. */}
      <section className="card">
        <div className="card-headbar">
          <div className="space-y-2">
            {/* R6 § F.2: bumped from space-y-1 (4px) to space-y-2 (8px) so
                the city/date caption breathes below the title (matches
                ProjectDetail.tsx's title-to-meta gap). */}
            <h1 className="h-page">{scout.name || "Untitled scout"}</h1>
            {heroSub && <div className="detail-meta">{heroSub}</div>}
          </div>
        </div>
        <div className="card-pad detail-2col--wide">
          {/* Wide column (70%) -- Overview + Details sub-sections.
              Amendment v6 § 5+6: column wrapper uses `space-y-9` for
              inter-section breathing only; the divider-rhythm rule
              (`[&>*]:py-N + first/last overrides`) moved INTO the
              Details card body so the Details `.card` chrome isn't
              affected by extra padding-top / pb-0 / column-level
              hairlines. `pr-6` keeps the wide column content off the
              70/30 gutter (v4 § 7). */}
          <div className="space-y-9 pr-6">
            {/* Overview sub-section -- always-editable textarea +
                Regenerate-in-eyebrow per amendment v3 § A + § G + § H + § I.
                Round 3 amendment v2 § 5: wraps in `.card` chrome with
                `card-headbar` matching Details. Header cluster (label +
                bullet + Regenerate) lives inside an inner flex div so
                the three items stay grouped left despite the card-headbar's
                `justify-content: space-between`. Textarea + loading
                branch live inside `.card-pad`. */}
            <section data-section="overview" className="card">
              <div className="card-headbar">
                <div className="flex items-center gap-2">
                  <span className="h-card">Overview</span>
                  {!cardDisabled && (
                    <>
                      <span className="text-muted-foreground">·</span>
                      <button
                        type="button"
                        data-regen-button="true"
                        disabled={overviewStatus !== "idle"}
                        onClick={() => {
                          // R6 § M.4: isEmpty reads the LOCAL draft (which
                          // includes any unsaved typing) instead of the
                          // persisted form value. A producer who types into
                          // the empty textarea + clicks Generate would
                          // otherwise have their draft discarded because the
                          // form was still empty under the dirty draft.
                          const isEmpty = (overviewDraft ?? "").trim() === "";
                          const overviewDirty =
                            overviewDraft !== (form.event_overview ?? "");
                          if (isEmpty) {
                            void runOverviewGeneration("generating");
                            return;
                          }
                          if (overviewDirty) {
                            setConfirmRegen(true);
                          } else {
                            void runOverviewGeneration("regenerating");
                          }
                        }}
                        className="inline-flex items-center gap-1.5 font-mono text-[11px] font-bold uppercase tracking-[0.06em] text-primary hover:underline disabled:opacity-50 disabled:hover:no-underline"
                      >
                        {overviewStatus === "regenerating" && (
                          <Loader2 className="h-3 w-3 animate-spin" />
                        )}
                        {/* R6 § M.4: label tracks the dirty draft as well,
                            so typing into an empty textarea flips the
                            button from "Generate" to "Regenerate". */}
                        {overviewStatus === "regenerating"
                          ? "Regenerating…"
                          : (overviewDraft ?? "").trim() === ""
                            ? "Generate"
                            : "Regenerate"}
                      </button>
                    </>
                  )}
                </div>
              </div>
              <div className="card-pad">
                {overviewStatus === "generating" ? (
                  <div className="flex items-center gap-3 rounded-md border border-border bg-[hsl(0_0%_10%)] px-4 py-6 text-sm text-muted-foreground">
                    <Loader2 className="h-4 w-4 animate-spin text-primary" />
                    Writing the event overview…
                  </div>
                ) : (
                  <Textarea
                    ref={overviewTextareaRef}
                    value={overviewDraft}
                    onChange={(e) => setOverviewDraft(e.target.value)}
                    onBlur={(e) => {
                      // Amendment v3 § G: if focus is moving to the Regenerate
                      // button, skip the auto-save so the button's onClick
                      // still sees the dirty diff and fires the confirm dialog.
                      const next = e.relatedTarget as HTMLElement | null;
                      if (next?.dataset?.regenButton === "true") return;
                      if (overviewDraft !== (form.event_overview ?? "")) {
                        void saveForm({
                          ...form,
                          event_overview: overviewDraft,
                        });
                      }
                    }}
                    disabled={cardDisabled || overviewStatus !== "idle"}
                    placeholder="A short overview of the activation, the audience, and the vibe."
                    // Amendment v4 § 6: `!`-prefix forces precedence over
                    // shadcn Textarea's default `bg-background` (#000).
                    className="!bg-[hsl(0_0%_10%)] resize-none overflow-hidden border-0"
                  />
                )}
              </div>
            </section>

            {/* Details sub-section -- 6 rows in amendment v3 § B order;
                standard divide-y hairlines (no custom overrides). v4 § 4:
                Details gets its own card chrome (border + card-headbar +
                card-pad); intentional card-inside-card. Overview / Dates /
                Generated Decks stay flat labeled blocks. */}
            <section data-section="details" className="card">
              <div className="card-headbar">
                <span className="h-card">Details</span>
              </div>
              {/* Amendment v6 § 4: divider rhythm bumped to 36px (py-9
                  = 36px above + below content). Only inside the Details
                  card body; the column-level wrappers now use space-y-9
                  for inter-section breathing. */}
              <div className="card-pad divide-y divide-border [&>*]:py-9 [&>:first-child]:pt-0 [&>:last-child]:pb-0">
                {/* Row 1: City + Neighborhoods + Venue Type (3-col) */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                  <BriefReportRow
                    label="City"
                    value={form.city}
                    isBlank={(v) => v.trim() === ""}
                    disabled={cardDisabled}
                    renderDisplay={(v) => (
                      <span className="text-foreground">{v.trim() || "Not set"}</span>
                    )}
                    renderEditor={(draft, set) => (
                      <RecordCombobox
                        source={{ kind: "lookup", table: "cities" }}
                        value={draft || null}
                        onChange={(v) => set(v ?? "")}
                        entityLabel="city"
                      />
                    )}
                    onSave={(v) => {
                      // City change clears target_neighborhoods (the pre-split
                      // composite editor's clearing rule, preserved across
                      // the row split). strict_neighborhoods_only stays
                      // untouched per amendment v3 § C.
                      const cleared = v !== form.city;
                      void saveForm({
                        ...form,
                        city: v,
                        target_neighborhoods: cleared
                          ? []
                          : form.target_neighborhoods,
                      });
                    }}
                  />

                  <BriefReportRow<{
                    neighborhoods: string[];
                    strict_neighborhoods_only: boolean;
                  }>
                    label={
                      // Amendment v6 § 7: STRICT renders at 10px (down
                      // from inherited 12px); `whitespace-nowrap` keeps
                      // it as one indivisible token; the parent
                      // `flex flex-wrap items-baseline` lets STRICT wrap
                      // to a new line at narrow viewports instead of
                      // overflowing into the Venue Type cell.
                      <span className="flex flex-wrap items-baseline gap-2">
                        <span>Neighborhoods</span>
                        {form.strict_neighborhoods_only && (
                          <span className="whitespace-nowrap text-[10px] text-primary">
                            *STRICT
                          </span>
                        )}
                      </span>
                    }
                    value={{
                      neighborhoods: form.target_neighborhoods,
                      strict_neighborhoods_only: form.strict_neighborhoods_only,
                    }}
                    isBlank={(v) => v.neighborhoods.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v.neighborhoods} />}
                    renderEditor={(draft, set) => (
                      <RecordCombobox
                        multi
                        multiValue={draft.neighborhoods}
                        onMultiChange={(v) => set({ ...draft, neighborhoods: v })}
                        source={{
                          kind: "lookup",
                          table: "neighborhoods",
                          parentScopeId: cityId,
                          parentScopeLabel: form.city || null,
                          parentScopeLabelKey: "City",
                        }}
                        entityLabel="neighborhood"
                        placeholder={cityId ? "Pick neighborhoods" : "Pick a city first"}
                        disabled={!cityId}
                      />
                    )}
                    editorLeftActions={(draft, set) => (
                      <label className="flex items-center gap-2 font-mono text-[12px] uppercase tracking-[0.06em] text-muted-foreground">
                        <Checkbox
                          checked={draft.strict_neighborhoods_only}
                          onCheckedChange={(c) =>
                            set({
                              ...draft,
                              strict_neighborhoods_only: c === true,
                            })
                          }
                        />
                        Strict?
                      </label>
                    )}
                    onSave={(v) =>
                      void saveForm({
                        ...form,
                        target_neighborhoods: v.neighborhoods,
                        strict_neighborhoods_only: v.strict_neighborhoods_only,
                      })
                    }
                  />

                  <BriefReportRow<string[]>
                    label="Venue Type"
                    value={form.venue_types}
                    isBlank={(v) => v.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v} />}
                    renderEditor={(draft, set) => (
                      <ChipMultiSelect value={draft} onChange={set} />
                    )}
                    onSave={(v) => void saveForm({ ...form, venue_types: v })}
                  />
                </div>

                {/* Row 2: Vibe + Aesthetic + Ideal Features (2-col) */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <BriefReportRow<string[]>
                    label="Vibe + Aesthetic"
                    value={form.vibe_aesthetic}
                    isBlank={(v) => v.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v} />}
                    renderEditor={(draft, set) => (
                      <TagInput
                        value={draft}
                        onChange={set}
                        placeholder="Add vibe tag, then Enter"
                      />
                    )}
                    onSave={(v) => void saveForm({ ...form, vibe_aesthetic: v })}
                  />

                  <BriefReportRow<string[]>
                    label="Ideal Features"
                    value={form.ideal_features}
                    isBlank={(v) => v.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v} />}
                    renderEditor={(draft, set) => (
                      <TagInput
                        value={draft}
                        onChange={set}
                        placeholder="catering kitchen, parking, projection mapping…"
                      />
                    )}
                    onSave={(v) => void saveForm({ ...form, ideal_features: v })}
                  />
                </div>

                {/* Row 3: Min. Square Footage + Expected Guest Count (2-col).
                    Sq. Footage Range retired in 5.12.14.3 R4 amendment v2 § D. */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <BriefReportRow<number | null>
                    label="Min. Square Footage"
                    value={form.sq_ft_minimum}
                    isBlank={(v) => v === null}
                    disabled={cardDisabled}
                    renderDisplay={(v) => (
                      <span className="text-foreground">
                        {v === null ? "Any" : `${v.toLocaleString()} sq ft`}
                      </span>
                    )}
                    renderEditor={(draft, set) => (
                      <div className="pt-1">
                        <Slider
                          value={[draft ?? 0]}
                          min={0}
                          max={SQ_FT_MAX}
                          step={SQ_FT_STEP}
                          onValueChange={([v]) => set(v === 0 ? null : v)}
                        />
                        <p className="mt-2 font-mono text-sm font-bold text-foreground">
                          {draft === null
                            ? "Any"
                            : `${draft.toLocaleString()} sq ft`}
                        </p>
                      </div>
                    )}
                    onSave={(v) => void saveForm({ ...form, sq_ft_minimum: v })}
                  />

                  <BriefReportRow
                    label="Expected Guest Count"
                    value={form.expected_guest_count}
                    isBlank={(v) => v.trim() === ""}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <span className="text-foreground">{v}</span>}
                    renderEditor={(draft, set) => (
                      <Input
                        inputMode="numeric"
                        value={draft}
                        onChange={(e) => set(e.target.value)}
                        placeholder="e.g. 150"
                        autoFocus
                      />
                    )}
                    onSave={(v) => void saveForm({ ...form, expected_guest_count: v })}
                  />
                </div>

                {/* Row 4: Priorities (composite) + # of Spaces (2-col) */}
                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <BriefReportRow<{
                    priority_location: PriorityLocation | null;
                    priority_cost: PriorityCost | null;
                  }>
                    label="Priorities"
                    value={{
                      priority_location: form.priority_location,
                      priority_cost: form.priority_cost,
                    }}
                    isBlank={(v) =>
                      v.priority_location === null && v.priority_cost === null
                    }
                    disabled={cardDisabled}
                    renderDisplay={(v) => (
                      <div className="space-y-1 text-foreground">
                        <div>
                          <span className="text-muted-foreground">Location: </span>
                          {v.priority_location
                            ? PRIORITY_LOCATION_LABEL[v.priority_location]
                            : "Not set"}
                        </div>
                        <div>
                          <span className="text-muted-foreground">Cost: </span>
                          {v.priority_cost
                            ? PRIORITY_COST_LABEL[v.priority_cost]
                            : "Not set"}
                        </div>
                      </div>
                    )}
                    renderEditor={(draft, set) => (
                      <div className="space-y-3">
                        <div className="space-y-1.5">
                          <div className="text-xs uppercase tracking-wider text-muted-foreground">
                            Location
                          </div>
                          <ToggleGroup
                            type="single"
                            value={draft.priority_location ?? ""}
                            onValueChange={(v) =>
                              set({
                                ...draft,
                                priority_location: v
                                  ? (v as PriorityLocation)
                                  : null,
                              })
                            }
                            className="justify-start"
                          >
                            <ToggleGroupItem value="high_foot_traffic">
                              High Foot Traffic
                            </ToggleGroupItem>
                            <ToggleGroupItem value="intimate_destination">
                              Intimate / Destination
                            </ToggleGroupItem>
                          </ToggleGroup>
                        </div>
                        <div className="space-y-1.5">
                          <div className="text-xs uppercase tracking-wider text-muted-foreground">
                            Cost
                          </div>
                          <ToggleGroup
                            type="single"
                            value={draft.priority_cost ?? ""}
                            onValueChange={(v) =>
                              set({
                                ...draft,
                                priority_cost: v ? (v as PriorityCost) : null,
                              })
                            }
                            className="justify-start"
                          >
                            <ToggleGroupItem value="lower_cost">
                              Lower Venue Costs
                            </ToggleGroupItem>
                            <ToggleGroupItem value="premium">
                              Premium Venue
                            </ToggleGroupItem>
                          </ToggleGroup>
                        </div>
                      </div>
                    )}
                    onSave={(v) => void saveForm({ ...form, ...v })}
                  />

                  <BriefReportRow<number | null>
                    label="# of Spaces"
                    value={form.activations_count}
                    // R6 § M.10: treat 0 as blank so a parsed
                    // `activations_count: 0` from the AI doesn't render as
                    // the literal "0" string in the display cell. The
                    // briefForm.ts parser-apply path also drops 0 values
                    // (see applyParsedFields guard).
                    isBlank={(v) => v === null || v === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => (
                      <span className="text-foreground">
                        {v !== null && v >= 10 ? "10+" : String(v)}
                      </span>
                    )}
                    renderEditor={(draft, set) => (
                      <div className="flex items-center gap-4 pt-1">
                        <Slider
                          value={[draft ?? 0]}
                          min={0}
                          max={10}
                          step={1}
                          onValueChange={([v]) => set(v === 0 ? null : v)}
                          className="flex-1"
                        />
                        <span className="w-12 shrink-0 text-right font-mono text-sm font-bold text-foreground">
                          {draft === null ? "TBD" : draft >= 10 ? "10+" : String(draft)}
                        </span>
                      </div>
                    )}
                    onSave={(v) => void saveForm({ ...form, activations_count: v })}
                  />
                </div>

                {/* Row 5: Event Objectives + Target Audience (2-col).
                    Amendment v5 § 6: THICKER divider above this row
                    (group separator between venue-spec rows 1-4 and the
                    event-narrative row). `!`-prefix overrides the parent
                    divide-y's 1px hairline with 2px + border-strong color. */}
                <div className="!border-t-2 !border-border-strong grid grid-cols-1 gap-4 sm:grid-cols-2">
                  <BriefReportRow<string[]>
                    label="Event Objectives"
                    value={form.objectives}
                    isBlank={(v) => v.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v} />}
                    renderEditor={(draft, set) => (
                      <TagInput
                        value={draft}
                        onChange={set}
                        placeholder="Add objective, then Enter"
                      />
                    )}
                    onSave={(v) => void saveForm({ ...form, objectives: v })}
                  />

                  <BriefReportRow<string[]>
                    label="Target Audience"
                    value={form.target_audience}
                    isBlank={(v) => v.length === 0}
                    disabled={cardDisabled}
                    renderDisplay={(v) => <TagList items={v} />}
                    renderEditor={(draft, set) => (
                      <TagInput
                        value={draft}
                        onChange={set}
                        placeholder="Add audience tag, then Enter"
                      />
                    )}
                    onSave={(v) => void saveForm({ ...form, target_audience: v })}
                  />
                </div>
                {/* Row 6 (Audience + Budget) deleted in amendment v5:
                    Audience moved to Row 5 alongside Event Objectives;
                    Budget moved to the right column inline with Live
                    Date(s). */}
              </div>
            </section>
          </div>

          {/* Narrow column (30%) -- Live Date(s) / Budget side-by-side at
              top, then Generated Decks. Amendment v6 § 5+6: same
              column-wrapper refactor as the wide column -- `space-y-9`
              for inter-section breathing only; divider rhythm lives
              inside the Details card body. */}
          <div className="space-y-9">
            {/* Amendment v5 § 2: Dates + Budget render side-by-side as
                their own labeled sub-sections inside a 2-col grid. The
                BriefReportRow inside each one renders the value alone
                (no label prop -- the section header IS the label).
                Amendment v6 § 3: absolutely-positioned vertical divider
                between the two cells, 75% of parent height, centered in
                the gutter. `position: relative` on the grid anchors it.
                Amendment v7: `gap-8` (32px) gives the divider ~15px of
                breathing room from each cell.
                Round 3 amendment v1 § 4: wrap the whole block in `.card`
                + `.card-pad` (no card-headbar; the LIVE DATE(S)/BUDGET
                eyebrows below carry the labels). */}
            <section className="card">
              <div className="card-pad">
                <div className="relative grid grid-cols-2 gap-8">
              <section data-section="dates">
                <div className="label-section pb-3">LIVE DATE(S)</div>
                <BriefReportRow
                  value={form.live_dates}
                  isBlank={(v) => v.trim() === ""}
                  disabled={cardDisabled}
                  renderDisplay={(v) => (
                    <span className="text-foreground">{v || "Not set"}</span>
                  )}
                  renderEditor={(draft, set) => (
                    <DateRangePicker
                      value={draft}
                      onChange={set}
                      placeholder="Select live dates"
                    />
                  )}
                  onSave={(v) => void saveForm({ ...form, live_dates: v })}
                />
              </section>

              {/* Amendment v6 § 3 + v7: 75%-height vertical divider in
                  the gutter between Dates + Budget. Centered horizontally
                  + vertically via translate. Absolute-positioned inside
                  the `relative` grid parent. v7 bumps line weight from
                  1px to 2px (`border-l-2`). */}
              <div
                aria-hidden="true"
                className="pointer-events-none absolute left-1/2 top-1/2 h-3/4 -translate-x-1/2 -translate-y-1/2 border-l-2 border-border"
              />

              {/* Amendment v7 follow-on: BUDGET is visually shorter than
                  LIVE DATE(S), so the symmetric gutter reads off-balance.
                  `pl-6` pushes BUDGET 24px further from the divider to
                  visually compensate for the narrower text. */}
              <section data-section="budget" className="pl-6">
                <div className="label-section pb-3">BUDGET</div>
                <BriefReportRow
                  value={form.budget_text}
                  isBlank={(v) => v.trim() === ""}
                  disabled={cardDisabled}
                  renderDisplay={(v) => (
                    <span className="text-foreground">{v}</span>
                  )}
                  renderEditor={(draft, set) => (
                    // R6 § D.2: auto-format budget editor input the same way
                    // BriefEvent does — strip non-digits, reformat with
                    // en-US thousands separator. Cursor may jump to end on
                    // mid-string edits; tolerated for now.
                    <Input
                      value={draft}
                      onChange={(e) => {
                        const digits = e.target.value.replace(/[^0-9]/g, "");
                        if (!digits) {
                          set("");
                          return;
                        }
                        const n = parseInt(digits, 10);
                        set(
                          Number.isFinite(n)
                            ? `$${n.toLocaleString("en-US")}`
                            : "",
                        );
                      }}
                      placeholder="$0"
                      autoFocus
                    />
                  )}
                  onSave={(v) => void saveForm({ ...form, budget_text: v })}
                />
              </section>
                </div>
              </div>
            </section>

            {/* Round 3 amendment v1 § 4 + v2 § 4: Generated Decks gets
                `.card` chrome with a `card-headbar` + `h-card` header,
                matching the Details card. */}
            <section data-section="generated-decks" className="card">
              <div className="card-headbar">
                <span className="h-card">Generated Decks</span>
              </div>
              <div className="card-pad">
                <GeneratedDecksCard decks={decks} />
              </div>
            </section>
          </div>
        </div>
      </section>

      {/* ---- Sticky footer (dynamic forward button per current_step) ----
          R6 § F.1: once the scout has generated at least one deck, the
          Go-to-Review forward affordance is hidden (there's nothing further
          forward; the producer can still reach Review via Scout Settings or
          direct nav). */}
      <div className="actionbar">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-6 py-4">
          <Link to="/venue-scout" className="crumb inline-flex items-center gap-1.5">
            <ArrowLeft className="h-3 w-3" /> Back
          </Link>
          {decks.length === 0 ? (
            <Button onClick={onForwardClick} disabled={confirming || isArchived}>
              {confirming ? "Saving…" : cta.label}
            </Button>
          ) : null}
        </div>
      </div>

      {/* Confirm-regen-on-dirty: producer clicked Regenerate with unsaved
          textarea edits. Preserved from the prior OverviewBlock behavior;
          hoisted into BriefReport when the Overview row dropped the
          BriefReportRow state machine in amendment v2. */}
      <AlertDialog open={confirmRegen} onOpenChange={setConfirmRegen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Discard your edits?</AlertDialogTitle>
            <AlertDialogDescription>
              Regenerating the overview will replace your unsaved edits with a fresh AI draft.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setConfirmRegen(false)}>
              Keep editing
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                setConfirmRegen(false);
                void runOverviewGeneration("regenerating");
              }}
            >
              Regenerate
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// Small pill list for tag-valued cards on the report. R6 amendment v1 § 3:
// chip text settles at 13px sitewide.
function TagList({ items }: { items: string[] }) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {items.map((it) => (
        <span
          key={it}
          className="inline-flex items-center rounded bg-input px-2 py-0.5 text-[13px] font-medium text-foreground"
        >
          {it}
        </span>
      ))}
    </div>
  );
}

