// Phase 4 Revision - Intake Step 3: Brief (inline-editable) + canonical Brief
// surface.
//
// Third step of the brief stepper AND the permanent Brief surface a scout
// keeps for the rest of its life. Renders the brief as a hero band + a stack
// of inline-editable cards. Every card flips to edit mode on click and
// persists on Save; the Event Overview block is auto-generated by
// vs-generate-brief-overview on first arrival (when event_overview is empty).
//
// Two modes:
//   - Intake mode (current_step === 'brief'): the footer shows Confirm &
//     Continue, which flips current_step brief -> sheet_prompt and advances.
//   - Permanent-surface mode (current_step past 'brief'): same page, but the
//     Confirm & Continue button is hidden. The Revisit nav surfaces this page
//     from elsewhere in the flow.
import { useCallback, useEffect, useRef, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ExternalLink, Loader2, Presentation } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Slider } from "@/components/ui/slider";
import { Checkbox } from "@/components/ui/checkbox";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { cn } from "@/lib/utils";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import {
  ScoutSettingsLink,
  ScoutStepThroughNav,
} from "@/components/venue-scout/ScoutChrome";
import { Stepper } from "@/components/venue-scout/Stepper";
import { TagInput } from "@/components/venue-scout/TagInput";
import { ChipMultiSelect } from "@/components/venue-scout/ChipMultiSelect";
import { stepToRoute } from "@/lib/venue-scout/format";
import {
  fromScout,
  toUpdate,
  type BriefFormState,
  type PriorityCost,
  type PriorityLocation,
} from "@/lib/venue-scout/briefForm";
import { briefIntake } from "@/lib/venue-scout/briefIntakeStore";
import type { Database } from "@/integrations/supabase/types";

type VsScoutRow = Database["public"]["Tables"]["vs_scouts"]["Row"];

type DeckEntry = {
  deck_id?: string;
  deck_name?: string;
  version?: number;
  generated_at?: string;
  venue_count?: number;
  slide_count?: number;
  edit_url?: string;
  embed_url?: string;
};

const SCOUT_SELECT =
  "id, client_name, event_name, live_dates, city, budget, event_overview, brief_data, current_step, archived_at, name, status, project_id, sheet_storage_path, derived_columns, generated_decks, deck_order, last_touched_at, created_at, created_by, updated_at, updated_by";

const SQ_FT_MAX = 10000;
const SQ_FT_STEP = 500;

const PRIORITY_LOCATION_LABEL: Record<PriorityLocation, string> = {
  high_foot_traffic: "High Foot Traffic",
  intimate_destination: "Intimate / Destination",
};
const PRIORITY_COST_LABEL: Record<PriorityCost, string> = {
  lower_cost: "Lower Venue Costs",
  premium: "Premium Venue",
};

function formatDeckDate(iso: string | undefined): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

function sqFtRangeLabel(min: number | null, max: number | null): string {
  return `${min === null ? "TBD" : min.toLocaleString()} to ${
    max === null ? "10,000+" : max.toLocaleString()
  } sq ft`;
}

// Client-side stub fallback for the Event Overview, mirroring the edge
// function's own fallback (spec § 6) for the case where the invoke itself
// fails (network) before the function can run.
function buildOverviewStub(form: BriefFormState): string {
  const where = form.city.trim() ? ` in ${form.city.trim()}` : "";
  const live = form.live_dates.trim() ? ` Live ${form.live_dates.trim()}.` : "";
  return `${form.event_name.trim() || "Event"} for ${
    form.client_name.trim() || "the client"
  }${where}.${live}`;
}

export default function BriefReport() {
  const { id: scoutId } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();

  const [scout, setScout] = useState<VsScoutRow | null>(null);
  const [form, setForm] = useState<BriefFormState | null>(null);
  const [confirming, setConfirming] = useState(false);
  const [overviewStatus, setOverviewStatus] = useState<
    "idle" | "generating" | "regenerating"
  >("idle");
  const overviewTriggeredRef = useRef(false);

  // Latest-form ref so async callbacks (overview generation) merge against the
  // current form, not a stale closure capture -- a card edit can land while
  // the overview is generating.
  const formRef = useRef<BriefFormState | null>(form);
  formRef.current = form;

  useEffect(() => {
    if (!scoutId) return;
    let active = true;
    (async () => {
      const { data, error } = await supabase
        .from("vs_scouts")
        .select(SCOUT_SELECT)
        .eq("id", scoutId)
        .maybeSingle();
      if (!active) return;
      if (error || !data) {
        toast({
          title: "Could not load scout",
          description: error?.message ?? "Scout not found",
          variant: "destructive",
        });
        return;
      }
      setScout(data as VsScoutRow);
      const f = fromScout(data as VsScoutRow);
      briefIntake.seed(scoutId, f);
      setForm(f);
    })();
    return () => {
      active = false;
    };
  }, [scoutId]);

  // Persist a form patch to the scout. Every inline card edit + the Overview
  // block route through here. Writes the full toUpdate payload (cheap: a few
  // columns + one jsonb) so the report stays consistent.
  const saveForm = useCallback(
    async (next: BriefFormState) => {
      if (!scoutId) return false;
      // Optimistic local update so the card flips back to display mode with
      // the new value immediately.
      setForm(next);
      briefIntake.commit(scoutId, next);
      const { error } = await supabase
        .from("vs_scouts")
        .update({
          ...toUpdate(next),
          last_touched_at: new Date().toISOString(),
          updated_by: user?.id ?? null,
        })
        .eq("id", scoutId);
      if (error) {
        toast({
          title: "Save failed",
          description: error.message,
          variant: "destructive",
        });
        return false;
      }
      return true;
    },
    [scoutId, user?.id],
  );

  // Event Overview generation. The edge function reads the scout's brief
  // fields, writes event_overview to the row, and returns it. On first
  // arrival (event_overview empty) we fire it once; the producer can also
  // re-fire it via the Regenerate link.
  const runOverviewGeneration = useCallback(
    async (mode: "generating" | "regenerating") => {
      if (!scoutId || !formRef.current) return;
      setOverviewStatus(mode);
      const { data, error } = await supabase.functions.invoke(
        "vs-generate-brief-overview",
        { body: { scout_id: scoutId } },
      );
      const responseError =
        error?.message ?? (data as { error?: string } | null)?.error ?? null;
      // Read the latest form AFTER the await -- a card edit may have landed
      // while the function was running.
      const latest = formRef.current;
      if (!latest) {
        setOverviewStatus("idle");
        return;
      }
      if (responseError) {
        // Invoke-level failure: the function never ran. Fall back to the
        // client stub so the producer always has a starting overview.
        const stub = buildOverviewStub(latest);
        await saveForm({ ...latest, event_overview: stub });
        toast({
          title: "Overview generation failed",
          description: "Filled a basic overview you can edit.",
          variant: "destructive",
        });
        setOverviewStatus("idle");
        return;
      }
      const overview =
        typeof (data as { event_overview?: unknown } | null)?.event_overview ===
        "string"
          ? ((data as { event_overview: string }).event_overview)
          : "";
      // The function already persisted event_overview; sync local state +
      // the cross-step store against the latest form inside the updater so a
      // concurrent card edit isn't clobbered.
      setForm((f) => {
        if (!f) return f;
        const next = { ...f, event_overview: overview };
        briefIntake.setForm(scoutId, next);
        return next;
      });
      setOverviewStatus("idle");
    },
    [scoutId, saveForm],
  );

  useEffect(() => {
    if (!form || overviewTriggeredRef.current) return;
    overviewTriggeredRef.current = true;
    if (form.event_overview.trim() === "") {
      void runOverviewGeneration("generating");
    }
    // runOverviewGeneration intentionally omitted: fire-once on first load.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form]);

  if (!scout || !form || !scoutId) {
    return <p className="text-sm text-muted-foreground">Loading…</p>;
  }

  const permanentSurface = scout.current_step !== "brief";
  const isArchived = scout.archived_at !== null;

  const decks = (
    Array.isArray(scout.generated_decks) ? scout.generated_decks : []
  ) as DeckEntry[];
  const decksNewestFirst = [...decks].reverse();

  const initials =
    (form.client_name.trim().slice(0, 2) || "?").toUpperCase();
  const heroSub = [form.city.trim(), form.live_dates.trim()]
    .filter(Boolean)
    .join(" · ");

  const requestConfirm = async () => {
    if (confirming) return;
    setConfirming(true);
    const { error } = await supabase
      .from("vs_scouts")
      .update({
        ...toUpdate(form),
        current_step: "sheet_prompt",
        last_touched_at: new Date().toISOString(),
        updated_by: user?.id ?? null,
      })
      .eq("id", scoutId);
    if (error) {
      setConfirming(false);
      toast({
        title: "Could not continue",
        description: error.message,
        variant: "destructive",
      });
      return;
    }
    briefIntake.reset();
    navigate(stepToRoute(scoutId, "sheet_prompt"));
  };

  const cardDisabled = isArchived;

  return (
    <div className="mx-auto max-w-3xl space-y-6 pb-24">
      <Link to="/venue-scout" className="crumb">
        ← Back to Venue Scout
      </Link>
      <header className="flex items-end justify-between gap-5">
        <div className="space-y-2">
          <h1 className="h-page">Brief</h1>
          <p className="text-sm text-muted-foreground">
            The locked brief. Click any card to edit it inline.
          </p>
        </div>
        <ScoutSettingsLink scoutId={scout.id} />
      </header>
      <ScoutStepThroughNav scoutId={scout.id} scout={scout} />
      <Stepper active={3} />

      {isArchived && (
        <div className="rounded-md border border-amber-500/40 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">
          This scout is archived. Restore it from the Venue Scout index to edit the brief.
        </div>
      )}

      {/* ---- Hero band ---- */}
      <div className="flex items-center gap-5 rounded-md border border-border bg-surface p-6">
        <div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-md bg-foreground text-2xl font-display font-extrabold text-background">
          {initials}
        </div>
        <div className="space-y-1">
          <div className="text-2xl font-display font-extrabold uppercase text-foreground">
            {form.event_name || "Untitled event"}
          </div>
          {heroSub && (
            <div className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
              {heroSub}
            </div>
          )}
        </div>
      </div>

      {/* ---- Generated Decks ---- */}
      {decksNewestFirst.length > 0 && (
        <section className="space-y-3">
          <div className="text-[12px] font-mono font-bold uppercase tracking-wider text-primary">
            Generated Decks
          </div>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {decksNewestFirst.map((deck, i) => {
              const meta = [
                formatDeckDate(deck.generated_at) &&
                  `Generated ${formatDeckDate(deck.generated_at)}`,
                typeof deck.venue_count === "number" &&
                  `${deck.venue_count} venues`,
                typeof deck.slide_count === "number" &&
                  `${deck.slide_count} slides`,
              ]
                .filter(Boolean)
                .join(" · ");
              return (
                <div
                  key={deck.deck_id ?? `${deck.deck_name}-${i}`}
                  className="flex flex-col gap-3 rounded-md border border-border bg-surface-alt p-4"
                >
                  <div className="flex items-start gap-3">
                    <Presentation className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                    <div className="min-w-0">
                      <div className="truncate text-sm font-bold text-foreground">
                        {deck.deck_name ??
                          `Deck${
                            typeof deck.version === "number"
                              ? ` v${deck.version}`
                              : ""
                          }`}
                      </div>
                      <div className="mt-0.5 text-xs text-muted-foreground">
                        {meta}
                      </div>
                    </div>
                  </div>
                  {deck.edit_url && (
                    <a
                      href={deck.edit_url}
                      target="_blank"
                      rel="noreferrer"
                      className="self-start"
                    >
                      <Button
                        variant={i === 0 ? "default" : "ghost"}
                        size="sm"
                        className="gap-1.5"
                      >
                        Open in Google Slides
                        <ExternalLink className="h-3.5 w-3.5" />
                      </Button>
                    </a>
                  )}
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* ---- Event Overview ---- */}
      <section className="space-y-3">
        <div className="text-[12px] font-mono font-bold uppercase tracking-wider text-primary">
          Event Overview
        </div>
        <OverviewBlock
          value={form.event_overview}
          status={overviewStatus}
          disabled={cardDisabled}
          onSave={(v) => void saveForm({ ...form, event_overview: v })}
          onRegenerate={() => void runOverviewGeneration("regenerating")}
        />
      </section>

      {/* ---- Event ---- */}
      <section className="space-y-3">
        <div className="text-[12px] font-mono font-bold uppercase tracking-wider text-primary">
          Event
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <ReportCard
            label="Live date(s)"
            value={form.live_dates}
            isBlank={(v) => v.trim() === ""}
            disabled={cardDisabled}
            renderDisplay={(v) => <span className="text-foreground">{v}</span>}
            renderEditor={(draft, set) => (
              <Input value={draft} onChange={(e) => set(e.target.value)} autoFocus />
            )}
            onSave={(v) => void saveForm({ ...form, live_dates: v })}
          />

          <ReportCard<{ install_dates: string; strike_dates: string }>
            label="Install / Strike"
            value={{
              install_dates: form.install_dates,
              strike_dates: form.strike_dates,
            }}
            isBlank={(v) =>
              v.install_dates.trim() === "" && v.strike_dates.trim() === ""
            }
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <div className="space-y-0.5 text-foreground">
                <div>
                  <span className="text-muted-foreground">Install: </span>
                  {v.install_dates.trim() || "Not set"}
                </div>
                <div>
                  <span className="text-muted-foreground">Strike: </span>
                  {v.strike_dates.trim() || "Not set"}
                </div>
              </div>
            )}
            renderEditor={(draft, set) => (
              <div className="space-y-2">
                <Input
                  value={draft.install_dates}
                  onChange={(e) =>
                    set({ ...draft, install_dates: e.target.value })
                  }
                  placeholder="Install dates"
                  autoFocus
                />
                <Input
                  value={draft.strike_dates}
                  onChange={(e) =>
                    set({ ...draft, strike_dates: e.target.value })
                  }
                  placeholder="Strike dates"
                />
              </div>
            )}
            onSave={(v) => void saveForm({ ...form, ...v })}
          />

          <ReportCard
            label="Budget"
            value={form.budget_text}
            isBlank={(v) => v.trim() === ""}
            disabled={cardDisabled}
            renderDisplay={(v) => <span className="text-foreground">{v}</span>}
            renderEditor={(draft, set) => (
              <Input
                value={draft}
                onChange={(e) => set(e.target.value)}
                placeholder="e.g. $50,000"
                autoFocus
              />
            )}
            onSave={(v) => void saveForm({ ...form, budget_text: v })}
          />

          <ReportCard<number | null>
            label="Activations / spaces"
            value={form.activations_count}
            isBlank={(v) => v === null}
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <span className="text-foreground">
                {v !== null && v >= 10 ? "10+" : String(v)}
              </span>
            )}
            renderEditor={(draft, set) => (
              <div className="flex items-center gap-4 pt-1">
                <Slider
                  value={[draft ?? 0]}
                  min={0}
                  max={10}
                  step={1}
                  onValueChange={([v]) => set(v === 0 ? null : v)}
                  className="flex-1"
                />
                <span className="w-12 shrink-0 text-right font-mono text-sm font-bold text-foreground">
                  {draft === null ? "TBD" : draft >= 10 ? "10+" : String(draft)}
                </span>
              </div>
            )}
            onSave={(v) => void saveForm({ ...form, activations_count: v })}
          />

          <ReportCard<string[]>
            label="Objectives"
            value={form.objectives}
            isBlank={(v) => v.length === 0}
            disabled={cardDisabled}
            fullWidth
            renderDisplay={(v) => <TagList items={v} />}
            renderEditor={(draft, set) => (
              <TagInput value={draft} onChange={set} placeholder="Add objective, then Enter" />
            )}
            onSave={(v) => void saveForm({ ...form, objectives: v })}
          />

          <ReportCard
            label="Target audience"
            value={form.target_audience}
            isBlank={(v) => v.trim() === ""}
            disabled={cardDisabled}
            fullWidth
            renderDisplay={(v) => (
              <span className="whitespace-pre-wrap text-foreground">{v}</span>
            )}
            renderEditor={(draft, set) => (
              <Textarea
                value={draft}
                onChange={(e) => set(e.target.value)}
                rows={4}
                autoFocus
              />
            )}
            onSave={(v) => void saveForm({ ...form, target_audience: v })}
          />

          <ReportCard
            label="Vibe / aesthetic"
            value={form.vibe_aesthetic}
            isBlank={(v) => v.trim() === ""}
            disabled={cardDisabled}
            fullWidth
            renderDisplay={(v) => (
              <span className="whitespace-pre-wrap text-foreground">{v}</span>
            )}
            renderEditor={(draft, set) => (
              <Textarea
                value={draft}
                onChange={(e) => set(e.target.value)}
                rows={4}
                autoFocus
              />
            )}
            onSave={(v) => void saveForm({ ...form, vibe_aesthetic: v })}
          />
        </div>
      </section>

      {/* ---- Venue ---- */}
      <section className="space-y-3">
        <div className="text-[12px] font-mono font-bold uppercase tracking-wider text-primary">
          Venue
        </div>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <ReportCard<{
            city: string;
            target_neighborhoods: string[];
            strict_neighborhoods_only: boolean;
          }>
            label="City & Target Neighborhoods"
            value={{
              city: form.city,
              target_neighborhoods: form.target_neighborhoods,
              strict_neighborhoods_only: form.strict_neighborhoods_only,
            }}
            isBlank={(v) =>
              v.city.trim() === "" && v.target_neighborhoods.length === 0
            }
            disabled={cardDisabled}
            fullWidth
            renderDisplay={(v) => (
              <div className="space-y-1.5 text-foreground">
                <div>{v.city.trim() || "Not set"}</div>
                {v.target_neighborhoods.length > 0 && (
                  <TagList items={v.target_neighborhoods} />
                )}
                <div className="text-xs text-muted-foreground">
                  Search strictly: {v.strict_neighborhoods_only ? "Yes" : "No"}
                </div>
              </div>
            )}
            renderEditor={(draft, set) => (
              <div className="space-y-3">
                <Input
                  value={draft.city}
                  onChange={(e) => set({ ...draft, city: e.target.value })}
                  placeholder="City"
                  autoFocus
                />
                <TagInput
                  value={draft.target_neighborhoods}
                  onChange={(v) => set({ ...draft, target_neighborhoods: v })}
                  placeholder="Add neighborhood, then Enter"
                />
                <label className="flex items-center gap-2 text-xs text-muted-foreground">
                  <Checkbox
                    checked={draft.strict_neighborhoods_only}
                    onCheckedChange={(c) =>
                      set({
                        ...draft,
                        strict_neighborhoods_only: c === true,
                      })
                    }
                  />
                  Search strictly these neighborhoods only?
                </label>
              </div>
            )}
            onSave={(v) => void saveForm({ ...form, ...v })}
          />

          <ReportCard<string[]>
            label="Venue type"
            value={form.venue_types}
            isBlank={(v) => v.length === 0}
            disabled={cardDisabled}
            renderDisplay={(v) => <TagList items={v} />}
            renderEditor={(draft, set) => (
              <ChipMultiSelect value={draft} onChange={set} />
            )}
            onSave={(v) => void saveForm({ ...form, venue_types: v })}
          />

          <ReportCard
            label="Expected guest count"
            value={form.expected_guest_count}
            isBlank={(v) => v.trim() === ""}
            disabled={cardDisabled}
            renderDisplay={(v) => <span className="text-foreground">{v}</span>}
            renderEditor={(draft, set) => (
              <Input
                inputMode="numeric"
                value={draft}
                onChange={(e) => set(e.target.value)}
                placeholder="e.g. 150"
                autoFocus
              />
            )}
            onSave={(v) => void saveForm({ ...form, expected_guest_count: v })}
          />

          <ReportCard<number | null>
            label="Minimum square footage"
            value={form.sq_ft_minimum}
            isBlank={(v) => v === null}
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <span className="text-foreground">
                {v === null ? "Any" : `${v.toLocaleString()} sq ft`}
              </span>
            )}
            renderEditor={(draft, set) => (
              <div className="pt-1">
                <Slider
                  value={[draft ?? 0]}
                  min={0}
                  max={SQ_FT_MAX}
                  step={SQ_FT_STEP}
                  onValueChange={([v]) => set(v === 0 ? null : v)}
                />
                <p className="mt-2 font-mono text-sm font-bold text-foreground">
                  {draft === null
                    ? "Any"
                    : `${draft.toLocaleString()} sq ft`}
                </p>
              </div>
            )}
            onSave={(v) => void saveForm({ ...form, sq_ft_minimum: v })}
          />

          <ReportCard<{ sq_ft_min: number | null; sq_ft_max: number | null }>
            label="Square footage range"
            value={{ sq_ft_min: form.sq_ft_min, sq_ft_max: form.sq_ft_max }}
            isBlank={(v) => v.sq_ft_min === null && v.sq_ft_max === null}
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <span className="text-foreground">
                {sqFtRangeLabel(v.sq_ft_min, v.sq_ft_max)}
              </span>
            )}
            renderEditor={(draft, set) => (
              <div className="pt-1">
                <Slider
                  value={[draft.sq_ft_min ?? 0, draft.sq_ft_max ?? SQ_FT_MAX]}
                  min={0}
                  max={SQ_FT_MAX}
                  step={SQ_FT_STEP}
                  onValueChange={([lo, hi]) =>
                    set({
                      sq_ft_min: lo === 0 ? null : lo,
                      sq_ft_max: hi === SQ_FT_MAX ? null : hi,
                    })
                  }
                />
                <p className="mt-2 font-mono text-sm font-bold text-foreground">
                  {sqFtRangeLabel(draft.sq_ft_min, draft.sq_ft_max)}
                </p>
              </div>
            )}
            onSave={(v) => void saveForm({ ...form, ...v })}
          />

          <ReportCard<string[]>
            label="Ideal features"
            value={form.ideal_features}
            isBlank={(v) => v.length === 0}
            disabled={cardDisabled}
            fullWidth
            renderDisplay={(v) => <TagList items={v} />}
            renderEditor={(draft, set) => (
              <TagInput
                value={draft}
                onChange={set}
                placeholder="catering kitchen, parking, projection mapping…"
              />
            )}
            onSave={(v) => void saveForm({ ...form, ideal_features: v })}
          />

          <ReportCard<PriorityLocation | null>
            label="Priority · Location"
            value={form.priority_location}
            isBlank={(v) => v === null}
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <span className="text-foreground">
                {v ? PRIORITY_LOCATION_LABEL[v] : ""}
              </span>
            )}
            renderEditor={(draft, set) => (
              <ToggleGroup
                type="single"
                value={draft ?? ""}
                onValueChange={(v) =>
                  set(v ? (v as PriorityLocation) : null)
                }
                className="justify-start"
              >
                <ToggleGroupItem value="high_foot_traffic">
                  High Foot Traffic
                </ToggleGroupItem>
                <ToggleGroupItem value="intimate_destination">
                  Intimate / Destination
                </ToggleGroupItem>
              </ToggleGroup>
            )}
            onSave={(v) => void saveForm({ ...form, priority_location: v })}
          />

          <ReportCard<PriorityCost | null>
            label="Priority · Cost"
            value={form.priority_cost}
            isBlank={(v) => v === null}
            disabled={cardDisabled}
            renderDisplay={(v) => (
              <span className="text-foreground">
                {v ? PRIORITY_COST_LABEL[v] : ""}
              </span>
            )}
            renderEditor={(draft, set) => (
              <ToggleGroup
                type="single"
                value={draft ?? ""}
                onValueChange={(v) => set(v ? (v as PriorityCost) : null)}
                className="justify-start"
              >
                <ToggleGroupItem value="lower_cost">
                  Lower Venue Costs
                </ToggleGroupItem>
                <ToggleGroupItem value="premium">Premium Venue</ToggleGroupItem>
              </ToggleGroup>
            )}
            onSave={(v) => void saveForm({ ...form, priority_cost: v })}
          />
        </div>
      </section>

      {/* ---- Sticky footer ---- */}
      <div className="sticky bottom-0 z-10 -mx-6 mt-6 border-t-2 border-primary/40 bg-background/90 px-6 py-4 backdrop-blur supports-[backdrop-filter]:bg-background/75">
        <div className="mx-auto flex max-w-3xl items-center justify-between gap-3">
          <Button
            variant="ghost"
            onClick={() => navigate(`/venue-scout/scouts/${scout.id}/brief/venue`)}
          >
            ← Back / Edit
          </Button>
          {!permanentSurface && (
            <Button onClick={requestConfirm} disabled={confirming || isArchived}>
              {confirming ? "Saving…" : "Confirm & Continue"}
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// OverviewBlock -- the auto-generated, inline-editable Event Overview. Saves
// on blur or via the explicit Save button when the draft diverges from the
// persisted value. Regenerate re-invokes vs-generate-brief-overview; if the
// producer has unsaved edits it confirms first.
// ---------------------------------------------------------------------------
function OverviewBlock({
  value,
  status,
  disabled,
  onSave,
  onRegenerate,
}: {
  value: string;
  status: "idle" | "generating" | "regenerating";
  disabled?: boolean;
  onSave: (v: string) => void;
  onRegenerate: () => void;
}) {
  const [draft, setDraft] = useState(value);
  const [confirmRegen, setConfirmRegen] = useState(false);

  // Keep the draft in sync when the persisted value changes from outside
  // (generation completes, regeneration completes).
  useEffect(() => {
    setDraft(value);
  }, [value]);

  const dirty = draft !== value;
  const busy = status !== "idle";

  if (status === "generating") {
    return (
      <div className="flex items-center gap-3 rounded-md border border-border bg-surface-alt px-4 py-6 text-sm text-muted-foreground">
        <Loader2 className="h-4 w-4 animate-spin text-primary" />
        Writing the event overview…
      </div>
    );
  }

  return (
    <div className="space-y-2 rounded-md border border-border bg-surface-alt p-4">
      <Textarea
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onBlur={() => {
          if (dirty) onSave(draft);
        }}
        rows={5}
        disabled={disabled || busy}
        placeholder="A short overview of the activation, the audience, and the vibe."
      />
      <div className="flex items-center justify-between gap-3">
        <button
          type="button"
          disabled={disabled || busy}
          onClick={() => {
            if (dirty) setConfirmRegen(true);
            else onRegenerate();
          }}
          className="inline-flex items-center gap-1.5 font-mono text-xs uppercase tracking-wider text-primary hover:underline disabled:opacity-50 disabled:hover:no-underline"
        >
          {status === "regenerating" && (
            <Loader2 className="h-3 w-3 animate-spin" />
          )}
          {status === "regenerating" ? "Regenerating…" : "Regenerate"}
        </button>
        {dirty && !busy && (
          <Button size="sm" onClick={() => onSave(draft)}>
            Save
          </Button>
        )}
      </div>

      <AlertDialog open={confirmRegen} onOpenChange={setConfirmRegen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Discard your edits?</AlertDialogTitle>
            <AlertDialogDescription>
              Regenerating the overview will replace your unsaved edits with a fresh AI draft.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel onClick={() => setConfirmRegen(false)}>
              Keep editing
            </AlertDialogCancel>
            <AlertDialogAction
              onClick={() => {
                setConfirmRegen(false);
                onRegenerate();
              }}
            >
              Regenerate
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// ---------------------------------------------------------------------------
// ReportCard -- inline-editable card. Click anywhere to flip to edit mode;
// Save commits, Cancel reverts to the last saved value, Escape cancels. The
// blank state ("Not provided") still flips to edit mode on click.
// ---------------------------------------------------------------------------
function ReportCard<T>({
  label,
  value,
  isBlank,
  renderDisplay,
  renderEditor,
  onSave,
  fullWidth,
  disabled,
}: {
  label: string;
  value: T;
  isBlank: (v: T) => boolean;
  renderDisplay: (v: T) => React.ReactNode;
  renderEditor: (draft: T, setDraft: (v: T) => void) => React.ReactNode;
  onSave: (v: T) => void;
  fullWidth?: boolean;
  disabled?: boolean;
}) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState<T>(value);

  const enter = () => {
    if (disabled || editing) return;
    setDraft(value);
    setEditing(true);
  };
  const commit = () => {
    onSave(draft);
    setEditing(false);
  };
  const cancel = () => setEditing(false);

  return (
    <div
      className={cn(
        "rounded-md border border-border bg-surface-alt p-4 transition-colors",
        fullWidth && "sm:col-span-2",
        !editing && !disabled && "cursor-pointer hover:border-primary/40",
      )}
      onClick={!editing ? enter : undefined}
      onKeyDown={
        editing
          ? (e) => {
              if (e.key === "Escape") cancel();
            }
          : undefined
      }
    >
      <div className="text-[11px] font-mono font-bold uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
      {editing ? (
        <div className="mt-2 space-y-3" onClick={(e) => e.stopPropagation()}>
          {renderEditor(draft, setDraft)}
          <div className="flex justify-end gap-2">
            <Button variant="ghost" size="sm" onClick={cancel}>
              Cancel
            </Button>
            <Button size="sm" onClick={commit}>
              Save
            </Button>
          </div>
        </div>
      ) : (
        <div className="mt-1.5 text-sm">
          {isBlank(value) ? (
            <span className="italic text-muted-foreground/60">
              Not provided
            </span>
          ) : (
            renderDisplay(value)
          )}
        </div>
      )}
    </div>
  );
}

// Small pill list for tag-valued cards on the report.
function TagList({ items }: { items: string[] }) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {items.map((it) => (
        <span
          key={it}
          className="inline-flex items-center rounded bg-input px-2 py-0.5 text-xs font-medium text-foreground"
        >
          {it}
        </span>
      ))}
    </div>
  );
}
