// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Phase 3.6.14: reverted from PKCE (flowType:"pkce") back to implicit flow.
// PKCE was returning 401 from the /auth/v1/token?grant_type=pkce exchange
// (code-verifier mismatch — root cause not yet diagnosed). Implicit flow
// returns the session in the URL hash (#access_token=...) which the
// supabase client parses on load via detectSessionInUrl. Hash survives
// Netlify's HTTP→HTTPS upgrade as long as Force HTTPS is on (it is), and
// useAuth.tsx's redirectTo is hardcoded to HTTPS so no scheme upgrade
// even needs to happen.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});